#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Pairwise vertical stitch:
- For each index i in [START_IDX..END_IDX],
  read ORIGINAL_DIR/smile_curve_segment_i.png and FILTERED_DIR/smile_curve_segment_i.png,
  stack them vertically, and save to OUTPUT_DIR/paired/smile_curve_pair_i.png

Defaults:
- ORIGINAL_DIR: your old plots (no filter)
- FILTERED_DIR: the filtered plots generated by the smoothing script (./output/plots)
- OUTPUT_DIR:  ./output/paired_plots
"""

import os
from pathlib import Path
from typing import Optional
from PIL import Image

# ---------------- Config ----------------
ORIGINAL_DIR = r"E:\\chrome-downloads\\20250926_plots\\20250926\\plots"
FILTERED_DIR = None  # None -> use script_dir/output/plots
FILE_PREFIX  = "smile_curve_segment_"
FILE_SUFFIX  = ".png"
START_IDX = 0
END_IDX   = 84  # inclusive

# Output directory relative to this script
SCRIPT_DIR = Path(__file__).resolve().parent
if FILTERED_DIR is None:
    FILTERED_DIR = str(SCRIPT_DIR / "output" / "plots")
OUTPUT_DIR = SCRIPT_DIR / "output" / "paired_plots"


# --------------- Helpers ----------------
def safe_open(path: Path) -> Optional[Image.Image]:
    if not path.exists():
        print(f"[WARN] Missing: {path}")
        return None
    try:
        return Image.open(path).convert("RGB")
    except Exception as e:
        print(f"[WARN] Failed to open {path}: {e}")
        return None


def vstack_two(top: Image.Image, bottom: Image.Image) -> Image.Image:
    # Make same width by white-padding smaller one
    max_w = max(top.width, bottom.width)
    h_top, h_bot = top.height, bottom.height

    def pad_to_width(im: Image.Image, w: int) -> Image.Image:
        if im.width == w:
            return im
        canvas = Image.new("RGB", (w, im.height), (255, 255, 255))
        x = (w - im.width) // 2
        canvas.paste(im, (x, 0))
        return canvas

    top_p = pad_to_width(top, max_w)
    bot_p = pad_to_width(bottom, max_w)

    out = Image.new("RGB", (max_w, h_top + h_bot), (255, 255, 255))
    out.paste(top_p, (0, 0))
    out.paste(bot_p, (0, h_top))
    return out


# --------------- Main -------------------
def main():
    orig_dir = Path(ORIGINAL_DIR)
    filt_dir = Path(FILTERED_DIR)
    out_dir  = OUTPUT_DIR
    out_dir.mkdir(parents=True, exist_ok=True)

    print(f"[INFO] Original: {orig_dir}")
    print(f"[INFO] Filtered: {filt_dir}")
    print(f"[INFO] Output:   {out_dir}")

    for i in range(START_IDX, END_IDX + 1):
        orig_path = orig_dir / f"{FILE_PREFIX}{i}{FILE_SUFFIX}"
        filt_path = filt_dir / f"{FILE_PREFIX}{i}{FILE_SUFFIX}"
        top  = safe_open(orig_path)
        bottom = safe_open(filt_path)
        if top is None or bottom is None:
            print(f"[SKIP] index {i} due to missing image(s).")
            continue
        stitched = vstack_two(top, bottom)
        out_path = out_dir / f"smile_curve_pair_{i}.png"
        stitched.save(out_path)
        print(f"[INFO] Saved: {out_path}  size={stitched.size}")


if __name__ == "__main__":
    main()
